# Do not edit this file until u know what u r doing---Maybe for 3G signal

$(call inherit-product, device/deovo/kai/full_kai.mk)

# Release name
PRODUCT_RELEASE_NAME := kai

# Preload bootanimation
TARGET_BOOTANIMATION_PRELOAD := true

TARGET_BOOTANIMATION_NAME := vertical-720x1280

# Inherit some common CM stuff.
$(call inherit-product, vendor/cm/config/common_full_phone.mk)
$(call inherit-product, vendor/cm/config/gsm.mk)

#Set build fingerprint / ID / Product Name ect.
PRODUCT_BUILD_PROP_OVERRIDES += PRODUCT_NAME=kai BUILD_FINGERPRINT="generic/kai/kai:4.0.4/IML74K/V03.025.2222:user/release-keys" PRIVATE_BUILD_DESC="kai-user 4.0.4 IML74K V03.025.2222 release-keys"

## Device identifier. This must come after all inclusions
PRODUCT_DEVICE := kai
PRODUCT_NAME := cm_kai
PRODUCT_BRAND := generic
PRODUCT_MODEL := deovo v5
PRODUCT_MANUFACTURER := NVIDIA
