#
# Copyright (C) 2012 The Android Open-Source Project
# Copyright (C) 2012 The CyanogenMod Project
# Copyright (C) 2012 mdeejay <mdjrussia@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Do not edit this file until u know what u r doing!

$(call inherit-product, $(SRC_TARGET_DIR)/product/languages_full.mk)

DEVICE_PACKAGE_OVERLAYS := device/deovo/kai/overlay

# Camera
PRODUCT_PACKAGES := \
    Camera \
    camera.tegra

# Files needed for boot image
PRODUCT_COPY_FILES := \
	device/deovo/kai/ramdisk/init.rc:root/init.rc \
	device/deovo/kai/ramdisk/init.kai.rc:root/init.kai.rc \
	device/deovo/kai/ramdisk/init.goldfish.rc:root/init.goldfish.rc \
	device/deovo/kai/ramdisk/init.nv_dev_board.usb.rc:root/init.nv_dev_board.usb.rc \
	device/deovo/kai/ramdisk/ueventd.rc:root/ueventd.rc \
	device/deovo/kai/ramdisk/ueventd.kai.rc:root/ueventd.kai.rc \
	device/deovo/kai/ramdisk/ueventd.goldfish.rc:root/ueventd.goldfish.rc \
	device/deovo/kai/ramdisk/init:root/init


# Prebuilt Audio/GPS/Camera/Wi-Fi configs
PRODUCT_COPY_FILES += \
	device/deovo/kai/dsp/asound.conf:system/etc/asound.conf \
	device/deovo/kai/configs/nvcamera.conf:system/etc/nvcamera.conf \
	device/deovo/kai/configs/media_profiles.xml:system/etc/media_profiles.xml \
	device/deovo/kai/configs/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
	device/deovo/kai/configs/p2p_supplicant.conf:system/etc/wifi/p2p_supplicant.conf \
	device/deovo/kai/configs/hostapd.conf:system/etc/wifi/hostapd.conf \
	device/deovo/kai/configs/TQS_S_2.6.ini:system/etc/firmware/ti-connectivity/TQS_S_2.6.ini \
	device/deovo/kai/configs/dhcpcd.conf:system/etc/dhcpcd.conf \
	device/deovo/kai/configs/dhcpcd.conf.new:system/etc/dhcpcd/dhcpcd.conf \
	device/deovo/kai/configs/dhcpd.conf:system/etc/dhcpd.conf \
	device/deovo/kai/configs/enctune.conf:system/etc/enctune.conf \
	device/deovo/kai/configs/ibss_supplicant.conf:system/etc/ibss_supplicant.conf

# BT config
PRODUCT_COPY_FILES += \
  system/bluetooth/data/main.conf:system/etc/bluetooth/main.conf

# Prebuilt Alsa configs
PRODUCT_COPY_FILES += \
	device/deovo/kai/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
	device/deovo/kai/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
	device/deovo/kai/usr/share/alsa/pcm/center_lfe.conf:system/usr/share/alsa/pcm/center_lfe.conf \
	device/deovo/kai/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
	device/deovo/kai/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
	device/deovo/kai/usr/share/alsa/pcm/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
	device/deovo/kai/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
	device/deovo/kai/usr/share/alsa/pcm/front.conf:system/usr/share/alsa/pcm/front.conf \
	device/deovo/kai/usr/share/alsa/pcm/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
	device/deovo/kai/usr/share/alsa/pcm/modem.conf:system/usr/share/alsa/pcm/modem.conf \
	device/deovo/kai/usr/share/alsa/pcm/rear.conf:system/usr/share/alsa/pcm/rear.conf \
	device/deovo/kai/usr/share/alsa/pcm/side.conf:system/usr/share/alsa/pcm/side.conf \
	device/deovo/kai/usr/share/alsa/pcm/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
	device/deovo/kai/usr/share/alsa/pcm/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
	device/deovo/kai/usr/share/alsa/pcm/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
	device/deovo/kai/usr/share/alsa/pcm/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
	device/deovo/kai/usr/share/alsa/pcm/surround71.conf:system/usr/share/alsa/pcm/surround71.conf

# Vold.fstab
PRODUCT_COPY_FILES += \
	device/deovo/kai/vold.fstab:system/etc/vold.fstab

# Input device configeration files
PRODUCT_COPY_FILES += \
	device/deovo/kai/usr/keylayout/qwerty.kl:system/usr/keylayout/qwerty.kl \
	device/deovo/kai/usr/keylayout/tegra-kbc.kl:system/usr/keylayout/tegra-kbc.kl \
	device/deovo/kai/usr/idc/ft5x0x_ts.idc:system/usr/idc/ft5x0x_ts.idc \
	device/deovo/kai/usr/idc/Goodix-TS.idc:system/usr/idc/Goodix-TS.idc \
	device/deovo/kai/usr/idc/qwerty.idc:system/usr/idc/qwerty.idc \
	device/deovo/kai/usr/idc/qwerty2.idc:system/usr/idc/qwerty2.idc \
	device/deovo/kai/usr/idc/raydium_ts.idc:system/usr/idc/raydium_ts.idc \
	device/deovo/kai/usr/idc/sensor00fn11.idc:system/usr/idc/sensor00fn11.idc

# Any prebuilt kernel modules
PRODUCT_COPY_FILES += \
    	device/deovo/kai/modules/baseband_usb_chr.ko:system/lib/modules/baseband_usb_chr.ko \
    	device/deovo/kai/modules/baseband-xmm-power2.ko:system/lib/modules/baseband-xmm-power2.ko \
    	device/deovo/kai/modules/bcm4329.ko:system/lib/modules/bcm4329.ko \
    	device/deovo/kai/modules/bcmdhd.ko:system/lib/modules/bcmdhd.ko \
    	device/deovo/kai/modules/btwilink.ko:system/lib/modules/btwilink.ko \
    	device/deovo/kai/modules/cfg80211.ko:system/lib/modules/cfg80211.ko \
		device/deovo/kai/modules/crc7.ko:system/lib/modules/crc7.ko \
		device/deovo/kai/modules/gps_drv.ko:system/lib/modules/gps_drv.ko \
		device/deovo/kai/modules/inv_mpu_bma250.ko:system/lib/modules/inv_mpu_bma250.ko \
		device/deovo/kai/modules/inv_mpu_hmc5883.ko:system/lib/modules/inv_mpu_hmc5883.ko \
		device/deovo/kai/modules/lib80211.ko:system/lib/modules/lib80211.ko \
		device/deovo/kai/modules/mac80211.ko:system/lib/modules/mac80211.ko \
		device/deovo/kai/modules/mpu3050.ko:system/lib/modules/mpu3050.ko \
    	device/deovo/kai/modules/raw_ip_net.ko:system/lib/modules/raw_ip_net.ko \
    	device/deovo/kai/modules/scsi_wait_scan.ko:system/lib/modules/scsi_wait_scan.ko \
    	device/deovo/kai/modules/tcrypt.ko:system/lib/modules/tcrypt.ko \
    	device/deovo/kai/modules/wl12xx.ko:system/lib/modules/wl12xx.ko \
    	device/deovo/kai/modules/wl12xx_sdio.ko:system/lib/modules/wl12xx_sdio.ko \
		device/deovo/kai/modules/compat/cfg80211.ko:system/lib/modules/compat/cfg80211.ko \
		device/deovo/kai/modules/compat/compat.ko:system/lib/modules/compat/compat.ko \
		device/deovo/kai/modules/compat/mac80211.ko:system/lib/modules/compat/mac80211.ko \
		device/deovo/kai/modules/compat/wl12xx.ko:system/lib/modules/compat/wl12xx.ko \
		device/deovo/kai/modules/compat/wl12xx_sdio.ko:system/lib/modules/compat/wl12xx_sdio.ko \
		device/deovo/kai/modules/compat/wl12xx_spi.ko:system/lib/modules/compat/wl12xx_spi.ko \
		device/deovo/kai/modules/compat/wl1251.ko:system/lib/modules/compat/wl1251.ko \
		device/deovo/kai/modules/compat/wl1251_sdio.ko:system/lib/modules/compat/wl1251_sdio.ko \
		device/deovo/kai/modules/compat/wl1251_spi.ko:system/lib/modules/compat/wl1251_spi.ko

# Torch
PRODUCT_PACKAGES += \
		Torch

# WI-Fi
PRODUCT_PACKAGES += \
		hostapd \
		hostapd_cli \
		calibrator \
		iw

# lights
PRODUCT_PACKAGES += \
        lights.kai

# Audio
PRODUCT_PACKAGES += \
		audio.a2dp.default \
        libaudioutils \
        libtinyalsa

# Live Wallpapers
PRODUCT_PACKAGES += \
		LiveWallpapers \
		LiveWallpapersPicker \
		VisualizationWallpapers \
		librs_jni

# Common
PRODUCT_PACKAGES += \
		make_ext4fs \
		setup_fs \
		l2ping \
		com.android.future.usb.accessory

# for bugmailer
ifneq ($(TARGET_BUILD_VARIANT),user)
		PRODUCT_PACKAGES += send_bug
		PRODUCT_COPY_FILES += \
		system/extras/bugmailer/bugmailer.sh:system/bin/bugmailer.sh \
		system/extras/bugmailer/send_bug:system/bin/send_bug
endif

# Permissions
PRODUCT_COPY_FILES += \
		device/deovo/kai/configs/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
		device/deovo/kai/configs/tablet_core_hardware.xml:system/etc/permissions/tablet_core_hardware.xml \
		device/deovo/kai/configs/android.hardware.camera.xml:system/etc/permissions/android.hardware.camera.xml \
		device/deovo/kai/configs/android.hardware.sensor.accelerometer.xml:system/etc/permissions/android.hardware.sensor.accelerometer.xml \
		device/deovo/kai/configs/android.hardware.sensor.compass.xml:system/etc/permissions/android.hardware.sensor.compass.xml \
		frameworks/base/data/etc/android.hardware.camera.flash-autofocus.xml:system/etc/permissions/android.hardware.camera.flash-autofocus.xml \
		frameworks/base/data/etc/android.hardware.camera.front.xml:system/etc/permissions/android.hardware.camera.front.xml \
		frameworks/base/data/etc/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
		frameworks/base/data/etc/android.hardware.nfc.xml:system/etc/permissions/android.hardware.nfc.xml \
		frameworks/base/data/etc/android.hardware.sensor.gyroscope.xml:system/etc/permissions/android.hardware.sensor.gyroscope.xml \
		frameworks/base/data/etc/android.hardware.sensor.light.xml:system/etc/permissions/android.hardware.sensor.light.xml \
		frameworks/base/data/etc/android.hardware.sensor.proximity.xml:system/etc/permissions/android.hardware.sensor.proximity.xml \
		frameworks/base/data/etc/android.hardware.touchscreen.multitouch.jazzhand.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \
		frameworks/base/data/etc/android.hardware.telephony.gsm.xml:system/etc/permissions/android.hardware.telephony.gsm.xml \
		frameworks/base/data/etc/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \
		frameworks/base/data/etc/android.hardware.usb.host.xml:system/etc/permissions/android.hardware.usb.host.xml \
		frameworks/base/data/etc/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
		frameworks/base/data/etc/android.hardware.wifi.direct.xml:system/etc/permissions/android.hardware.wifi.direct.xml

#Do not delete these properties below!
PRODUCT_PROPERTY_OVERRIDES += \
        ro.com.google.locationfeatures=1 \
        ro.setupwizard.enable_bypass=1 \
        dalvik.vm.execution-mode=int:jit \
        dalvik.vm.lockprof.threshold=500 \
        dalvik.vm.dexopt-flags=m=y \
		dalvik.vm.dexopt-data-only=1

# Tegra 3 specific overrides
PRODUCT_PROPERTY_OVERRIDES += \
		persist.tegra.nvmmlite=1 \
		tf.enable=y

# We have enough storage space to hold precise GC data
PRODUCT_TAGS += dalvik.gc.type-precise

PRODUCT_BUILD_PROP_OVERRIDES += BUILD_UTC_DATE=0

PRODUCT_AAPT_CONFIG := normal hdpi xhdpi
PRODUCT_AAPT_PREF_CONFIG := xhdpi
PRODUCT_LOCALES += xhdpi


$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base_telephony.mk)
$(call inherit-product-if-exists, vendor/deovo/kai/kai-vendor.mk)
$(call inherit-product, frameworks/base/build/phone-xhdpi-1024-dalvik-heap.mk)
